ssh -l LockeZ node-0.16nodes.spark-pg0.wisc.cloudlab.us 'sudo pkill rundb'
ssh -l LockeZ node-1.16nodes.spark-pg0.wisc.cloudlab.us 'sudo pkill rundb'
ssh -l LockeZ node-2.16nodes.spark-pg0.wisc.cloudlab.us 'sudo pkill rundb'
ssh -l LockeZ node-3.16nodes.spark-pg0.wisc.cloudlab.us 'sudo pkill rundb'
ssh -l LockeZ node-8.16nodes.spark-pg0.wisc.cloudlab.us 'sudo pkill rundb'
ssh -l LockeZ node-9.16nodes.spark-pg0.wisc.cloudlab.us 'sudo pkill rundb'
ssh -l LockeZ node-10.16nodes.spark-pg0.wisc.cloudlab.us 'sudo pkill rundb'
ssh -l LockeZ node-11.16nodes.spark-pg0.wisc.cloudlab.us 'sudo pkill rundb'
